#! /usr/bin/env python
import sys
import glob
import re

# check for tabs
for file in ["meld"] + glob.glob("*.py"):
	txt = open(file).read()
	firsttab = txt.find('\t')
	if firsttab != -1:
		line = len( txt[:firsttab].split("\n") )
		print "%s:%i:Tabs detected" % (file, line)
		sys.exit(1)

# fix glade files - glade strips directory names from pixmaps :-(
def add_pixmap_dir(matchobj):
	ret = matchobj.group(1)
	ico = matchobj.group(2)
	if ico.find("/") == -1:
		print "Changed", ico, "to",
		newico = "pixmaps/"+ico
		ret = ret.replace(ico, newico)
		print newico
	return ret 

icon_re = re.compile(r'(<property name="(?:icon|logo)">([^<]+)</property>)')
for file in glob.glob("glade2/*.glade"):
	txt = open(file).read()
	newtxt = icon_re.sub(add_pixmap_dir, txt)
	if txt != newtxt:
		open(file,"w").write(newtxt)
	
