#! /usr/bin/env python

### Copyright (C) 2002-2003 Stephen Kennedy <steve9000@users.sf.net>

### This program is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; either version 2 of the License, or
### (at your option) any later version.

### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.

### You should have received a copy of the GNU General Public License
### along with this program; if not, write to the Free Software
### Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import os
import sys

def system(s):
	print s
	os.system(s)

tag = "release-%s" % sys.argv[1].replace(".","_")
release = "meld-" + sys.argv[1]
export = "cvs -d :pserver:anonymous@cvs1:2401/cvsroot/meld -q -z3 export -r %s -d %s meld" % (tag, release)
system(export)
targz = release + ".tgz "
tar = "tar cvfz %s %s" % (targz, release)
system(tar)
clean = "rm -rf " + release
system(clean)
upload = 'lftp -c "open upload; cd incoming; put %s"' % targz
system(upload)

