#! /usr/bin/python

import os
import sys
import string

def system(s):
	print s
	os.system(s)

tag = "release-%s" % string.replace(sys.argv[1],".","_")
release = "meld-" + sys.argv[1]
export = "cvs -d :pserver:anonymous@cvs1:2401/cvsroot/meld -q -z3 export -r %s -d %s meld" % (tag, release)
system(export)
targz = release + ".tgz "
tar = "tar cvfz %s %s" % (targz, release)
system(tar)
clean = "rm -rf " + release
system(clean)
upload = 'lftp -c "open upload; cd incoming; put %s"' % targz
system(upload)

