
all:
	inkscape hicolor/scalable/apps/org.gnome.meld.svg -w 48 -h 48 -e hicolor/48x48/apps/org.gnome.meld.png
	convert -background transparent hicolor/48x48/apps/org.gnome.meld.png -define icon:auto-resize=16,22,32,48 org.gnome.meld.ico
