#!/usr/bin/python

import sys
import os
import subprocess

def getScriptPath():
    return os.path.dirname(os.path.realpath(sys.argv[0]))

arglist = []

if len(sys.argv) > 1:
  try:
    arglist.append(os.path.abspath(sys.argv[1]));
  except:
    arglist.append(sys.argv[1])

if len(sys.argv) > 2:
  try:
    arglist.append(os.path.abspath(sys.argv[2]));
  except:
    arglist.append(sys.argv[2])

if len(sys.argv) > 3:
  try:
    arglist.append(os.path.abspath(sys.argv[3]));
  except:
    arglist.append(sys.argv[3])

MELDPATH = getScriptPath() + "/Meld-bin"
APPPATH = os.path.abspath(os.path.join(getScriptPath(), '..'))

environment = dict(os.environ,
  **{ "DYLD_LIBRARY_PATH" : APPPATH+"/Resources/lib:"+ APPPATH+"/Frameworks",
      "LANG": "C"})

p = subprocess.call([MELDPATH] + arglist, env= environment)
