#! /usr/bin/env python

### Copyright (C) 2002-2003 Stephen Kennedy <stevek@gnome.org>

### This program is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; either version 2 of the License, or
### (at your option) any later version.

### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.

### You should have received a copy of the GNU General Public License
### along with this program; if not, write to the Free Software
### Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
### USA.

import sys
import glob
import re

# check for tabs
for file in ["meld"] + glob.glob("*.py") + glob.glob("vc/*.py"):
	txt = open(file).read()
	firsttab = txt.find('\t')
	if firsttab != -1:
		line = len( txt[:firsttab].split("\n") )
		print "%s:%i:Tabs detected" % (file, line)
		sys.exit(1)

# fix glade files - glade strips directory names from icons :-(
def add_pixmap_dir(matchobj):
	ret = matchobj.group(1)
	ico = matchobj.group(2)
	if ico.find("/") == -1:
		print "Changed", ico, "to",
		newico = "../icons/"+ico
		ret = ret.replace(ico, newico)
		print newico
	return ret

icon_re = re.compile(r'(<property name="(?:icon|logo|pixbuf)">([^<]+)</property>)')
for file in glob.glob("data/ui/*.glade"):
	txt = open(file).read()
	newtxt = icon_re.sub(add_pixmap_dir, txt)
	if txt != newtxt:
		open(file,"w").write(newtxt)
	
version = re.search('^version\s*=\s*"([^"]+)"', open("meldapp.py").read(), re.M).group(1)
if open("NEWS").readline().find("meld-"+version) == -1:
	print "No NEWS entry for", version
