#! /usr/bin/env python

### Copyright (C) 2002-2003 Stephen Kennedy <stevek@gnome.org>

### This program is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; either version 2 of the License, or
### (at your option) any later version.

### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.

### You should have received a copy of the GNU General Public License
### along with this program; if not, write to the Free Software
### Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
### USA.

import os
import sys
import string

SFORGE = 0
GNOME = 1

host = GNOME

if host == SFORGE:
    cvsroot = ":pserver:anonymous@cvs1:2401/cvsroot/meld"
    upload = 'lftp -c "open upload; cd incoming; put %s"'
else:
    cvsroot = ":pserver:anonymous@anoncvs.gnome.org:/cvs/gnome"
    upload = 'install-module %s'

def system(s):
    print s
    if os.system(s) != 0:
        raise "Command error!"

# gnome release
tag = "release-%s" % string.replace(sys.argv[1], ".", "_")
release = "meld-" + sys.argv[1]
#export = "cvs -d %s -q -z3 export -r %s -d %s meld" % (cvsroot, tag, release)
export = "svn export http://svn.gnome.org/svn/meld/tags/%s %s" % (tag, release)
system(export)
targz = release + ".tar.gz"
tar = "tar cvfz %s %s" % (targz, release)
system(tar)
clean = "rm -rf " + release
system(clean)
system(upload % targz)

